- Radios/radio3/index.html
- Radios/radio3/style.css
> I have added the radio button

- Forms/form4/LoginForm.css
- Forms/form4/loginForm.html
> Added a Login Form

- Buttons/button3/index.html
- Buttons/button3/style.css
Added Button 3 as Per Issue #1
> Added Button 3 as Per Issue #1

- Loaders/loader4/main.html
- Loaders/loader4/styles.css
> added a new loader

- Loaders/loader5/index.html
- Loaders/loader5/style.css
I have added new loader. Please check it
> Added new loader

- Forms/form5/index.html
- Forms/form5/style.css
Resolve Issue #11 
Created a new form5 folder and added HTML and CSS file.
> new form added

- Buttons/button4/index.html
- Buttons/button4/style.css
#What does this PR do?
This PR added a new button on the project
fixes #21
> added new button

- Inputs/input3/index.html
- Inputs/input3/style.css
Fix: Added new input control #14 .
> #Fix: Added new Input component #14

- search_button.html
> Created search_button.html

- Cards/card3/index.html
- Cards/card3/style.css
resolved issue : #15
Created  new Cards using CSS hover effect and HTML in a new folder named card3.
> new cards added

- Navbar/navbar1/index.html
- Navbar/navbar1/style.css
Hi @parag477 ,
I hope you're doing well. I wanted to share the changes I've made in this pull request. I've added a responsive top navigation bar on our website.
Here's a brief overview of the changes:
Implemented a responsive design for the top navigation bar to ensure it adapts to various screen sizes, making our website more user-friendly on both desktop and mobile devices.
Ensured that the navigation items are well-organized and easy to access for our users.
Please feel free to review the code changes and provide any feedback or suggestions you may have. Your input is highly valued.
Thank you for taking the time to review my pull request. I look forward to your feedback and am ready to make any necessary adjustments.
Best regards,
@Saroj-pradhan
> adding a responsive top navbar

- .vscode/settings.json
- Buttons/searchButton/search_button.html
the bug  "adding search_button.html files to buttons folder #38 fixed" kindly accept the pr
> adding search_button.html files to buttons folder #38 fixed

- Radios/radio4/index.html
- Radios/radio4/styles.css
Issue  #51
Description:
Added an example of a Radio Button where one has to select their gender and their age group. It is a simple implementation of radio buttons with simple Styling using CSS.
> added a new radio button

- RadioButton/index.html
- Added Radio Buttons showing their Functionality along with simple Styling using CSS
Fixes #45 by @parag477 
Added a basic example of Radio Button where one has to select their Profession. It is very simple implementation for beginners along with commenting and simple Styling using CSS.
> Added an example of Radio Buttons

- Buttons/button6/index.html
- Buttons/button6/style.css
Added new button
Issue #43 
Thanks as i am starting and learning open source contribution ❤
> feat-new-button

- Preloader/preloader_1/index.html
This PR creates a Preloader component to enhance user experience in our web development components collection.
Solves issue #57 
https://github.com/parag477/Amazing-Webdev-Components/assets/107195487/6d1501e7-00dd-447b-b280-4bfde7f0773c
> Create a preloader component issue #57

- Switch/Bootstrap_Switch/index.html
- Switch/Bootstrap_Switch/style.css
- Switch/Material_UI_Switch/index.html
- Switch/Material_UI_Switch/style.css
- Switch/Metro_UI_Switch/index.html
- Switch/Metro_UI_Switch/style.css
This folder contains different Switch UI likes Material UI, Bootstrap UI, Metro UI. This enable developers to quickly take their desired UI..
-- Issue Fixed : #61
> Switch Component added

- Preloader/preloader_2/index.html
This PR adds another Preloader component to enhance user experience in our web development components collection.
Solves issue #57 #63 
https://github.com/parag477/Amazing-Webdev-Components/assets/107195487/6bde0536-06a4-4be0-870b-f70739d687df
> Create an another preloader #issue#57

- Buttons/button7/index.html
- Buttons/button7/styles.css
> fixes issue #16

- Forms/form7/index.html
- Forms/form7/style.css
Added: #69 
Added a form that is build with the help of bootstrap
> add#69: Form added

- Navbar/Navbar2/index.html
- Navbar/Navbar2/style.css
Added Responsive Navbar 
https://www.loom.com/share/a65f28b7607540cfabe566fbf38eff69?sid=45c31907-7e95-4469-984f-f81ffd6ab9b5
Please review my code and accept my pull request under Hacktoberfest
> feat: Add responsive navigation bar

- .vscode/settings.json
- Buttons/button8/index.html
- Buttons/button8/style.css
Added a new Button ---> Button_8 in `Buttons` folder. Inconveniences are duly regretted.
> [ADD]:Added_new_Button

- Forms/form/index.html
- Forms/form/styles.css
Issue #74 
Description:
Added a simple example of a login form with CSS styling.
> Added Login form

- Loaders/loader6/index.html
Hi @parag477 
i just added a loader animation in the repo, CSS is embedded in a style tag in the HTML file itself.
result: 
Kindly accept my PR under Hacktoberfest :)
> Added Loader

- Radios/radio5/index.html
- Radios/radio5/styles.css
**Added Unique Radio Button Options**
**Testing:**
I tested these changes in Chrome and Edge browsers to ensure they display correctly.
**Screenshot:**
Closes #12
> New Radio button added in repo

- Preloader/preloader_4/index.html
- Preloader/preloader_4/style.css
I saw that there only few preloaders, so i wanted to add more.
Please accept my PR under hacktoberfest if possible.
#34 
Thanks.
> FEAT: added new preloader

- Buttons/Button10/index.html
- Buttons/Button10/style.css
Added : #98 
Added an html, css button component
> Added Button Added

- Forms/form9/index.html
- Forms/form9/style.css
> bootstrap_form #91

- lightning buttons/index.html
- lightning buttons/styles.css
> Added lightning button

- Navbar/Navbar2/index.html
- Navbar/Navbar2/style.css
Fixing issue #103 
I attempted to enhance the appearance of the responsive navbar to make it more visually appealing.
Added a typewriter effect to "Amazing web components' and zoom effect on hover in navbar components.
> Added typewriter and zoom effects in responsive navbar

- Forms/form11/index.html
- Forms/form11/index.js
- Forms/form11/style.css
added #111 
Made a registration form using html, css and vanilla javascript.
> registration form added

- Buttons/Button11/index.html
- Buttons/Button11/style.css
I know we already have 10 buttons but why not seek for more options if we can. Therefore added the 11th button.
fixes issue #117
> added button-11

- Forms/form 12/index.html
- Forms/form 12/index.js
- Forms/form 12/style.css
added: #119 
Made a registration form using Html ,CSS and Javascript
> add: registration form

- Preloader/preloader_5/index.html
- Preloader/preloader_5/style.css
added : #113 
Made a preloader in the form of sun rays using simple HTML and CSS.
> [ADD] : preloader

- search_button.html
> Update search_button.html to center

- Buttons/Button12/index.html
Added a button with heartbeat animation.
> heartbeat button

- .vscode/settings.json
- Navbar/navbar5/navbar5.html
Added new navbar5.html with eye catching insights and colors.
also made the navbar responsive on mobile view 
made the hamburger clickable and show the buttons
> made new navbar5.html with responsive view and eye catching sights

- Forms/Dynamic_Form/index.html
- Forms/Dynamic_Form/script.js
- Forms/Dynamic_Form/style.css
This PR closes #116 .
Created a Form Containing Full Name, Age, City as Input Fields.
Have a Submit Button.
By clicking it, our Input will be displayed on another half of Screen
After Clicking Submit Button:
> Added Dynamic Form 

- Buttons/Button13/index.html
- Buttons/Button13/style.css
Added: #131 
Created a button using html and css
> button created

- Buttons/Button14/Index.html
- Buttons/Button14/Style.css
Added a new button which says "click me".
Before : 
After Hover :
> Added a new button

- loginPage/index.html
- loginPage/style.css
> Added login page

- Accordion/index.html
- Accordion/script.js
- Accordion/style.css
> Added accordion

- Modals/index.html
- Modals/script.js
- Modals/style.css
>  Added a modal

- Forms/form13/index.html
- Forms/form13/style.css
Closes #146 
Hey @parag477 I have added a new form in this repository. Please accept and merge it.
> added form13 🦄

- Notification Badge with Dynamic Count/Badge.html
A versatile notification badge that displays a dynamic count of unread notifications. It updates based on user interaction, such as dismissing notifications.
> notification badge component with dynamic count

- Buttons/Button10/style.css
- Buttons/Button12/index.html
- Buttons/Button13/style.css
- Buttons/button1/style.css
- Navbar/navbar6/index.html
added new vertical navbar
centered few buttons (verticaly & horizontaly)
> new vertical navbar & button fixes 

- Collapsible FAQ Section with Animation/faqsection.html
This component creates a collapsible FAQ section where each answer smoothly reveals itself upon clicking a question. This is useful for FAQ pages or other sections where users need information in expandable lists.
>  Collapsible FAQ Section with Animation

- Collapsible FAQ Section with Animation/faq2.html
better faq buttons
Closes #158
> new faq buttons format

- Collapsible FAQ Section with Animation/faq2.html
- Notification Badge with Dynamic Count/badge2.html
Key Features and Details:
Dynamic Notification Badge:
The notification badge count is dynamically updated based on the button clicks, incrementing or decrementing the count as needed.
Animation for Count Change:
The badge briefly scales up to provide a smooth visual indicator whenever the count changes. The animated class is added temporarily to apply this effect.
Pulse Animation on Icon Hover:
The notification bell has a subtle hover rotation effect for interactivity.
Responsive Button Styling:
The buttons for testing the badge count (increase/decrease) are styled with color transitions and smooth animations.
> New Notification button with counter
